2024-03-14 18:51:43,922 — main.py:59 -     get_qna_response() — INFO — [] - answer_id:cd203b36-e205-11ee-8993-acde48001122
2024-03-14 18:51:43,922 — main.py:63 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:cd203b36-e205-11ee-8993-acde48001122
2024-03-14 18:54:52,820 — main.py:135 -     get_qna_response() — ERROR — [] - InternalError: get_relevant_documents() missing 1 required positional argument: 'self' :Traceback (most recent call last):;  File "/Users/reverma/git/custom-rag-pipeline/main.py", line 82, in get_qna_response;    bot.prepare();  File "/Users/reverma/git/custom-rag-pipeline/src/answer_generator.py", line 25, in prepare;    context, prompt_type = self.context_handler.prepare_context();  File "/Users/reverma/git/custom-rag-pipeline/src/components/context_handler.py", line 16, in prepare_context;    context = self.search_handler.search_for_top_articles(user_query);  File "/Users/reverma/git/custom-rag-pipeline/src/components/search_handler.py", line 30, in search_for_top_articles;    chosen_sections = self.doc_retriever.get_relevant_documents(;TypeError: get_relevant_documents() missing 1 required positional argument: 'self';
2024-03-14 18:59:10,108 — main.py:59 -     get_qna_response() — INFO — [] - answer_id:d712ebe2-e206-11ee-8993-acde48001122
2024-03-14 18:59:10,109 — main.py:63 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:d712ebe2-e206-11ee-8993-acde48001122
2024-03-14 19:01:09,492 — main.py:135 -     get_qna_response() — ERROR — [] - InternalError: get_relevant_documents() missing 1 required positional argument: 'self' :Traceback (most recent call last):;  File "/Users/reverma/git/custom-rag-pipeline/main.py", line 82, in get_qna_response;    bot.prepare();  File "/Users/reverma/git/custom-rag-pipeline/src/answer_generator.py", line 25, in prepare;    context, prompt_type = self.context_handler.prepare_context();  File "/Users/reverma/git/custom-rag-pipeline/src/components/context_handler.py", line 16, in prepare_context;    context = self.search_handler.search_for_top_articles(user_query);  File "/Users/reverma/git/custom-rag-pipeline/src/components/search_handler.py", line 30, in search_for_top_articles;    chosen_sections = self.doc_retriever.get_relevant_documents(;TypeError: get_relevant_documents() missing 1 required positional argument: 'self';
2024-03-14 19:01:15,602 — main.py:59 -     get_qna_response() — INFO — [] - answer_id:21dfad18-e207-11ee-8993-acde48001122
2024-03-14 19:01:15,603 — main.py:63 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:21dfad18-e207-11ee-8993-acde48001122
2024-03-14 19:07:40,174 — main.py:59 -     get_qna_response() — INFO — [] - answer_id:0718b492-e208-11ee-9486-acde48001122
2024-03-14 19:07:40,174 — main.py:63 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:0718b492-e208-11ee-9486-acde48001122
2024-03-14 19:13:06,801 — main.py:59 -     get_qna_response() — INFO — [] - answer_id:c9c811a4-e208-11ee-ad12-acde48001122
2024-03-14 19:13:06,801 — main.py:63 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:c9c811a4-e208-11ee-ad12-acde48001122
2024-03-14 19:13:16,549 — main.py:135 -     get_qna_response() — ERROR — [] - InternalError: get_relevant_documents() missing 1 required positional argument: 'self' :Traceback (most recent call last):;  File "/Users/reverma/git/custom-rag-pipeline/main.py", line 82, in get_qna_response;    bot.prepare();  File "/Users/reverma/git/custom-rag-pipeline/src/answer_generator.py", line 25, in prepare;    context, prompt_type = self.context_handler.prepare_context();  File "/Users/reverma/git/custom-rag-pipeline/src/components/context_handler.py", line 16, in prepare_context;    context = self.search_handler.search_for_top_articles(user_query);  File "/Users/reverma/git/custom-rag-pipeline/src/components/search_handler.py", line 30, in search_for_top_articles;    chosen_sections = self.doc_retriever.get_relevant_documents();TypeError: get_relevant_documents() missing 1 required positional argument: 'self';
2024-03-14 19:18:33,867 — main.py:59 -     get_qna_response() — INFO — [] - answer_id:8cba4d4e-e209-11ee-8221-acde48001122
2024-03-14 19:18:33,868 — main.py:63 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:8cba4d4e-e209-11ee-8221-acde48001122
2024-03-14 19:18:49,079 — main.py:135 -     get_qna_response() — ERROR — [] - InternalError: '>' not supported between instances of 'int' and 'NoneType' :Traceback (most recent call last):;  File "/Users/reverma/git/custom-rag-pipeline/main.py", line 82, in get_qna_response;    bot.prepare();  File "/Users/reverma/git/custom-rag-pipeline/src/answer_generator.py", line 25, in prepare;    context, prompt_type = self.context_handler.prepare_context();  File "/Users/reverma/git/custom-rag-pipeline/src/components/context_handler.py", line 16, in prepare_context;    context = self.search_handler.search_for_top_articles(user_query);  File "/Users/reverma/git/custom-rag-pipeline/src/components/search_handler.py", line 43, in search_for_top_articles;    len("".join(chosen_sections).split()) > max_context_tokens;TypeError: '>' not supported between instances of 'int' and 'NoneType';
2024-03-14 19:20:11,259 — main.py:59 -     get_qna_response() — INFO — [] - answer_id:c6c74014-e209-11ee-b604-acde48001122
2024-03-14 19:20:11,260 — main.py:63 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:c6c74014-e209-11ee-b604-acde48001122
2024-03-14 19:20:17,468 — main.py:135 -     get_qna_response() — ERROR — [] - InternalError: '>' not supported between instances of 'int' and 'NoneType' :Traceback (most recent call last):;  File "/Users/reverma/git/custom-rag-pipeline/main.py", line 82, in get_qna_response;    bot.prepare();  File "/Users/reverma/git/custom-rag-pipeline/src/answer_generator.py", line 25, in prepare;    context, prompt_type = self.context_handler.prepare_context();  File "/Users/reverma/git/custom-rag-pipeline/src/components/context_handler.py", line 16, in prepare_context;    context = self.search_handler.search_for_top_articles(user_query);  File "/Users/reverma/git/custom-rag-pipeline/src/components/search_handler.py", line 43, in search_for_top_articles;    len("".join(chosen_sections).split()) > max_context_tokens;TypeError: '>' not supported between instances of 'int' and 'NoneType';
2024-03-14 19:21:14,272 — main.py:59 -     get_qna_response() — INFO — [] - answer_id:ec562b1a-e209-11ee-b604-acde48001122
2024-03-14 19:21:14,273 — main.py:63 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:ec562b1a-e209-11ee-b604-acde48001122
2024-03-14 19:21:17,438 — main.py:135 -     get_qna_response() — ERROR — [] - InternalError: '>' not supported between instances of 'int' and 'NoneType' :Traceback (most recent call last):;  File "/Users/reverma/git/custom-rag-pipeline/main.py", line 82, in get_qna_response;    bot.prepare();  File "/Users/reverma/git/custom-rag-pipeline/src/answer_generator.py", line 25, in prepare;    context, prompt_type = self.context_handler.prepare_context();  File "/Users/reverma/git/custom-rag-pipeline/src/components/context_handler.py", line 16, in prepare_context;    context = self.search_handler.search_for_top_articles(user_query);  File "/Users/reverma/git/custom-rag-pipeline/src/components/search_handler.py", line 43, in search_for_top_articles;    len("".join(chosen_sections).split()) > max_context_tokens;TypeError: '>' not supported between instances of 'int' and 'NoneType';
2024-03-14 19:21:24,336 — main.py:59 -     get_qna_response() — INFO — [] - answer_id:f255da38-e209-11ee-b604-acde48001122
2024-03-14 19:21:24,337 — main.py:63 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:f255da38-e209-11ee-b604-acde48001122
2024-03-14 19:22:48,666 — main.py:59 -     get_qna_response() — INFO — [] - answer_id:24998f76-e20a-11ee-98b1-acde48001122
2024-03-14 19:22:48,666 — main.py:63 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:24998f76-e20a-11ee-98b1-acde48001122
2024-03-14 19:22:52,326 — search_handler.py:49 - search_for_top_articles() — INFO — [] - Info - retrieved_doc - answer_id:24998f76-e20a-11ee-98b1-acde48001122
2024-03-14 19:23:47,640 — main.py:59 -     get_qna_response() — INFO — [] - answer_id:47c04652-e20a-11ee-a5d5-acde48001122
2024-03-14 19:23:47,641 — main.py:63 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:47c04652-e20a-11ee-a5d5-acde48001122
2024-03-14 19:24:05,575 — search_handler.py:49 - search_for_top_articles() — INFO — [] - Info - retrieved_doc - answer_id:47c04652-e20a-11ee-a5d5-acde48001122
2024-03-14 19:27:25,247 — main.py:59 -     get_qna_response() — INFO — [] - answer_id:c9747e7a-e20a-11ee-a5d5-acde48001122
2024-03-14 19:27:25,247 — main.py:63 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:c9747e7a-e20a-11ee-a5d5-acde48001122
2024-03-14 19:27:25,248 — search_handler.py:49 - search_for_top_articles() — INFO — [] - Info - retrieved_doc - answer_id:c9747e7a-e20a-11ee-a5d5-acde48001122
2024-03-14 19:27:38,685 — main.py:59 -     get_qna_response() — INFO — [] - answer_id:d177145c-e20a-11ee-a5d5-acde48001122
2024-03-14 19:27:38,685 — main.py:63 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:d177145c-e20a-11ee-a5d5-acde48001122
2024-03-14 19:27:38,686 — search_handler.py:49 - search_for_top_articles() — INFO — [] - Info - retrieved_doc - answer_id:d177145c-e20a-11ee-a5d5-acde48001122
2024-03-14 19:41:42,190 — main.py:59 -     get_qna_response() — INFO — [] - answer_id:c83bb85a-e20c-11ee-a5d5-acde48001122
2024-03-14 19:41:42,192 — main.py:63 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:c83bb85a-e20c-11ee-a5d5-acde48001122
2024-03-14 19:41:42,192 — search_handler.py:49 - search_for_top_articles() — INFO — [] - Info - retrieved_doc - answer_id:c83bb85a-e20c-11ee-a5d5-acde48001122
2024-03-14 22:33:34,442 — main.py:63 -     get_qna_response() — INFO — [] - answer_id:cad06ac6-e224-11ee-9be2-acde48001122
2024-03-14 22:33:34,443 — main.py:67 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:cad06ac6-e224-11ee-9be2-acde48001122
2024-03-14 23:17:14,074 — main.py:63 -     get_qna_response() — INFO — [] - answer_id:e43c8872-e22a-11ee-91e9-acde48001122
2024-03-14 23:17:14,074 — main.py:67 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:e43c8872-e22a-11ee-91e9-acde48001122
2024-03-14 23:17:24,667 — main.py:140 -     get_qna_response() — ERROR — [] - InternalError: Can't instantiate abstract class VectorDBRetriever with abstract methods _retrieve :Traceback (most recent call last):;  File "/Users/reverma/git/custom-rag-pipeline/main.py", line 85, in get_qna_response;    bot = QAGenerator(service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/answer_generator.py", line 18, in __init__;    self.context_handler = ContextHandler(self.service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/components/context_handler.py", line 14, in __init__;    self.search_handler = SearchHandler(service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/components/search_handler.py", line 11, in __init__;    self.doc_retriever = self._get_doc_retriever();  File "/Users/reverma/git/custom-rag-pipeline/src/components/search_handler.py", line 17, in _get_doc_retriever;    return VectorDBRetriever(self.service_state, similarity_top_k=top_n);TypeError: Can't instantiate abstract class VectorDBRetriever with abstract methods _retrieve;
2024-03-14 23:21:10,337 — main.py:63 -     get_qna_response() — INFO — [] - answer_id:710f7836-e22b-11ee-a971-acde48001122
2024-03-14 23:21:10,338 — main.py:67 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:710f7836-e22b-11ee-a971-acde48001122
2024-03-14 23:21:14,165 — main.py:123 -     get_qna_response() — ERROR — [] - InternalError: 'ServiceState' object is not subscriptable :Traceback (most recent call last):;  File "/Users/reverma/git/custom-rag-pipeline/main.py", line 85, in get_qna_response;    bot = QAGenerator(service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/answer_generator.py", line 18, in __init__;    self.context_handler = ContextHandler(self.service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/components/context_handler.py", line 14, in __init__;    self.search_handler = SearchHandler(service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/components/search_handler.py", line 11, in __init__;    self.doc_retriever = self._get_doc_retriever();  File "/Users/reverma/git/custom-rag-pipeline/src/components/search_handler.py", line 17, in _get_doc_retriever;    retriever = VectorDBRetriever(self.service_state, similarity_top_k=top_n);  File "/Users/reverma/git/custom-rag-pipeline/src/components/doc_retriever.py", line 45, in __init__;    self.embed_model = DataHandler(self.service_state['config']);TypeError: 'ServiceState' object is not subscriptable;
2024-03-14 23:21:40,764 — main.py:63 -     get_qna_response() — INFO — [] - answer_id:83324c50-e22b-11ee-a971-acde48001122
2024-03-14 23:21:40,765 — main.py:67 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:83324c50-e22b-11ee-a971-acde48001122
2024-03-14 23:23:39,523 — main.py:123 -     get_qna_response() — ERROR — [] - InternalError: 'ServiceState' object is not subscriptable :Traceback (most recent call last):;  File "/Users/reverma/git/custom-rag-pipeline/main.py", line 85, in get_qna_response;    bot = QAGenerator(service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/answer_generator.py", line 18, in __init__;    self.context_handler = ContextHandler(self.service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/components/context_handler.py", line 14, in __init__;    self.search_handler = SearchHandler(service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/components/search_handler.py", line 11, in __init__;    self.doc_retriever = self._get_doc_retriever();  File "/Users/reverma/git/custom-rag-pipeline/src/components/search_handler.py", line 17, in _get_doc_retriever;    retriever = VectorDBRetriever(self.service_state, similarity_top_k=top_n);  File "/Users/reverma/git/custom-rag-pipeline/src/components/doc_retriever.py", line 45, in __init__;    self.embed_model = DataHandler(self.service_state['config']);TypeError: 'ServiceState' object is not subscriptable;
2024-03-14 23:23:58,894 — main.py:63 -     get_qna_response() — INFO — [] - answer_id:d5872796-e22b-11ee-a971-acde48001122
2024-03-14 23:23:58,895 — main.py:67 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:d5872796-e22b-11ee-a971-acde48001122
2024-03-14 23:24:59,663 — main.py:123 -     get_qna_response() — ERROR — [] - InternalError: 'ServiceState' object is not subscriptable :Traceback (most recent call last):;  File "/Users/reverma/git/custom-rag-pipeline/main.py", line 85, in get_qna_response;    bot = QAGenerator(service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/answer_generator.py", line 18, in __init__;    self.context_handler = ContextHandler(self.service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/components/context_handler.py", line 14, in __init__;    self.search_handler = SearchHandler(service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/components/search_handler.py", line 11, in __init__;    self.doc_retriever = self._get_doc_retriever();  File "/Users/reverma/git/custom-rag-pipeline/src/components/search_handler.py", line 17, in _get_doc_retriever;    retriever = VectorDBRetriever(self.service_state, similarity_top_k=top_n);  File "/Users/reverma/git/custom-rag-pipeline/src/components/doc_retriever.py", line 45, in __init__;    self.embed_model = DataHandler(self.service_state['config']);TypeError: 'ServiceState' object is not subscriptable;
2024-03-14 23:25:18,801 — main.py:63 -     get_qna_response() — INFO — [] - answer_id:05280e3e-e22c-11ee-a971-acde48001122
2024-03-14 23:25:18,802 — main.py:67 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:05280e3e-e22c-11ee-a971-acde48001122
2024-03-14 23:25:51,196 — main.py:123 -     get_qna_response() — ERROR — [] - InternalError: 'ServiceState' object is not subscriptable :Traceback (most recent call last):;  File "/Users/reverma/git/custom-rag-pipeline/main.py", line 85, in get_qna_response;    bot = QAGenerator(service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/answer_generator.py", line 18, in __init__;    self.context_handler = ContextHandler(self.service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/components/context_handler.py", line 14, in __init__;    self.search_handler = SearchHandler(service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/components/search_handler.py", line 11, in __init__;    self.doc_retriever = self._get_doc_retriever();  File "/Users/reverma/git/custom-rag-pipeline/src/components/search_handler.py", line 17, in _get_doc_retriever;    retriever = VectorDBRetriever(self.service_state, similarity_top_k=top_n);  File "/Users/reverma/git/custom-rag-pipeline/src/components/doc_retriever.py", line 45, in __init__;    self.embed_model = DataHandler(self.service_state['config']);TypeError: 'ServiceState' object is not subscriptable;
2024-03-14 23:26:20,044 — main.py:63 -     get_qna_response() — INFO — [] - answer_id:29a8f746-e22c-11ee-a971-acde48001122
2024-03-14 23:26:20,045 — main.py:67 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:29a8f746-e22c-11ee-a971-acde48001122
2024-03-14 23:26:37,741 — main.py:123 -     get_qna_response() — ERROR — [] - InternalError: 'ServiceState' object is not subscriptable :Traceback (most recent call last):;  File "/Users/reverma/git/custom-rag-pipeline/main.py", line 85, in get_qna_response;    bot = QAGenerator(service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/answer_generator.py", line 18, in __init__;    self.context_handler = ContextHandler(self.service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/components/context_handler.py", line 14, in __init__;    self.search_handler = SearchHandler(service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/components/search_handler.py", line 11, in __init__;    self.doc_retriever = self._get_doc_retriever();  File "/Users/reverma/git/custom-rag-pipeline/src/components/search_handler.py", line 17, in _get_doc_retriever;    retriever = VectorDBRetriever(self.service_state, similarity_top_k=top_n);  File "/Users/reverma/git/custom-rag-pipeline/src/components/doc_retriever.py", line 45, in __init__;    self.embed_model = DataHandler(self.service_state['config']);TypeError: 'ServiceState' object is not subscriptable;
2024-03-14 23:27:55,863 — main.py:63 -     get_qna_response() — INFO — [] - answer_id:62c5d9e0-e22c-11ee-a971-acde48001122
2024-03-14 23:27:55,864 — main.py:67 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:62c5d9e0-e22c-11ee-a971-acde48001122
2024-03-14 23:28:04,004 — main.py:123 -     get_qna_response() — ERROR — [] - InternalError: 'ServiceState' object is not subscriptable :Traceback (most recent call last):;  File "/Users/reverma/git/custom-rag-pipeline/main.py", line 85, in get_qna_response;    bot = QAGenerator(service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/answer_generator.py", line 18, in __init__;    self.context_handler = ContextHandler(self.service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/components/context_handler.py", line 14, in __init__;    self.search_handler = SearchHandler(service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/components/search_handler.py", line 11, in __init__;    self.doc_retriever = self._get_doc_retriever();  File "/Users/reverma/git/custom-rag-pipeline/src/components/search_handler.py", line 17, in _get_doc_retriever;    retriever = VectorDBRetriever(self.service_state, similarity_top_k=top_n);  File "/Users/reverma/git/custom-rag-pipeline/src/components/doc_retriever.py", line 45, in __init__;    self.embed_model = DataHandler(self.service_state['config']);TypeError: 'ServiceState' object is not subscriptable;
2024-03-14 23:28:18,772 — main.py:63 -     get_qna_response() — INFO — [] - answer_id:706d6e5a-e22c-11ee-a971-acde48001122
2024-03-14 23:28:18,773 — main.py:67 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:706d6e5a-e22c-11ee-a971-acde48001122
2024-03-14 23:28:36,153 — main.py:123 -     get_qna_response() — ERROR — [] - InternalError: 'ServiceState' object is not subscriptable :Traceback (most recent call last):;  File "/Users/reverma/git/custom-rag-pipeline/main.py", line 85, in get_qna_response;    bot = QAGenerator(service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/answer_generator.py", line 18, in __init__;    self.context_handler = ContextHandler(self.service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/components/context_handler.py", line 14, in __init__;    self.search_handler = SearchHandler(service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/components/search_handler.py", line 11, in __init__;    self.doc_retriever = self._get_doc_retriever();  File "/Users/reverma/git/custom-rag-pipeline/src/components/search_handler.py", line 17, in _get_doc_retriever;    retriever = VectorDBRetriever(self.service_state, similarity_top_k=top_n);  File "/Users/reverma/git/custom-rag-pipeline/src/components/doc_retriever.py", line 45, in __init__;    self.embed_model = DataHandler(self.service_state['config']);TypeError: 'ServiceState' object is not subscriptable;
2024-03-14 23:29:31,494 — main.py:63 -     get_qna_response() — INFO — [] - answer_id:9bc5f676-e22c-11ee-a971-acde48001122
2024-03-14 23:29:31,495 — main.py:67 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:9bc5f676-e22c-11ee-a971-acde48001122
2024-03-14 23:38:10,097 — main.py:63 -     get_qna_response() — INFO — [] - answer_id:d0e2687a-e22d-11ee-a4a1-acde48001122
2024-03-14 23:38:10,098 — main.py:67 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:d0e2687a-e22d-11ee-a4a1-acde48001122
2024-03-14 23:38:20,942 — main.py:123 -     get_qna_response() — ERROR — [] - InternalError: 'ServiceState' object is not subscriptable :Traceback (most recent call last):;  File "/Users/reverma/git/custom-rag-pipeline/main.py", line 85, in get_qna_response;    bot = QAGenerator(service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/answer_generator.py", line 18, in __init__;    self.search_handler = SearchHandler(self.service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/components/search_handler.py", line 11, in __init__;    self.doc_retriever = self._get_doc_retriever();  File "/Users/reverma/git/custom-rag-pipeline/src/components/search_handler.py", line 17, in _get_doc_retriever;    retriever = VectorDBRetriever(self.service_state, similarity_top_k=top_n);  File "/Users/reverma/git/custom-rag-pipeline/src/components/doc_retriever.py", line 45, in __init__;    query_bundle.query_str;TypeError: 'ServiceState' object is not subscriptable;
2024-03-14 23:40:02,823 — main.py:63 -     get_qna_response() — INFO — [] - answer_id:14132300-e22e-11ee-a4a1-acde48001122
2024-03-14 23:40:02,824 — main.py:67 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:14132300-e22e-11ee-a4a1-acde48001122
2024-03-14 23:40:31,303 — main.py:123 -     get_qna_response() — ERROR — [] - InternalError: 'ServiceState' object is not subscriptable :Traceback (most recent call last):;  File "/Users/reverma/git/custom-rag-pipeline/main.py", line 85, in get_qna_response;    bot = QAGenerator(service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/answer_generator.py", line 18, in __init__;    self.search_handler = SearchHandler(self.service_state);  File "/Users/reverma/git/custom-rag-pipeline/src/components/search_handler.py", line 11, in __init__;  File "/Users/reverma/git/custom-rag-pipeline/src/components/search_handler.py", line 17, in _get_doc_retriever;    return retriever;  File "/Users/reverma/git/custom-rag-pipeline/src/components/doc_retriever.py", line 45, in __init__;    query_bundle.query_str;TypeError: 'ServiceState' object is not subscriptable;
